#!/bin/bash
# record cpu load

LOAD5=$(cat /proc/loadavg | cut -f1 -d' ')
CPUNUM=$(grep -c ^processor /proc/cpuinfo)

# keep 10,080 lines, at 1 minute per line that's 7 days
tail -n 10079 ./data/cpu-load > ./temp/cpu-load
echo -e $(date +"%D_%H:%M") $(echo "$LOAD5/$CPUNUM*100" | bc -l | xargs printf "%.2f") >> ./temp/cpu-load
mv -f ./temp/cpu-load ./data/cpu-load

