#!/bin/bash
# record disk space
tail -n 287 ./data/disk-space > ./temp/disk-space
echo -e $(date +"%D_%H:%M") $(df / | awk 'END{print $3/$2*100}' | xargs printf '%.3f\n') >> ./temp/disk-space
mv -f ./temp/disk-space ./data/disk-space

