#!/bin/bash
# record memory usage
tail -n 10079 ./data/memory > ./temp/memory
echo -e $(date +"%D_%H:%M") $(free | grep Mem | awk '{print ($7/$2-1)*-100}') >> ./temp/memory
mv -f ./temp/memory ./data/memory

