#!/bin/bash
# record memory usage
tail -n 10079 ./data/players > ./temp/players
echo -e $(date +"%D_%H:%M") $(find /home/crawl/DGL/dgldir/inprogress/ -name '*.ttyrec' | wc -l) >> ./temp/players
mv -f ./temp/players ./data/players

